# Generated by Django 5.2.10 on 2026-09-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JewelrySKU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("BGL", "BGL - Bangles / Kadas"),
                            ("BRC", "BRC - Bracelet"),
                            ("NCK", "NCK - Necklace / Choker"),
                            ("EAR", "EAR - Earrings"),
                            ("SET", "SET - Complete Set / Combo"),
                            ("JHK", "JHK - Jhumkas"),
                            ("RNG", "RNG - Rings"),
                            ("PAY", "PAY - Anklet / Payal"),
                            ("TIK", "TIK - Maang Tikka"),
                        ],
                        default="BGL",
                        max_length=10,
                    ),
                ),
                (
                    "style",
                    models.CharField(
                        default="ADC", help_text="e.g. ADC, 1GP, OXS", max_length=20
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="LOVE",
                        help_text="e.g. LOVE, VINE, PEACOCK",
                        max_length=50,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("GLD", "GLD - Golden"),
                            ("RBYGRN", "RBYGRN - Ruby & Emerald Green"),
                            ("GRN", "GRN - Emerald Green"),
                            ("MRN", "MRN - Maroon / Ruby"),
                            ("ROSE", "ROSE - Rose Gold"),
                            ("SLV", "SLV - Silver / Rhodium"),
                            ("MTC", "MTC - Multi-Color"),
                            ("WHT", "WHT - White / Pearl"),
                            ("BLK", "BLK - Black"),
                            ("BLU", "BLU - Royal Blue"),
                            ("PNK", "PNK - Baby Pink"),
                        ],
                        default="GLD",
                        max_length=20,
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        default="2.4",
                        help_text="e.g. 2.4, 2.6, ADJ, FREE",
                        max_length=20,
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        default="001", help_text="e.g. 001", max_length=10
                    ),
                ),
                ("sku", models.CharField(editable=False, max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
