# Generated by Django 5.2.10 on 2026-09-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sku_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jewelrysku",
            name="name",
            field=models.CharField(
                default="", help_text="e.g. LOVE, VINE, PEACOCK", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="jewelrysku",
            name="number",
            field=models.CharField(default="", help_text="e.g. 001", max_length=10),
        ),
        migrations.AlterField(
            model_name="jewelrysku",
            name="size",
            field=models.CharField(
                default="", help_text="e.g. 2.4, 2.6, ADJ, FREE", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="jewelrysku",
            name="style",
            field=models.CharField(
                default="", help_text="e.g. ADC, 1GP, OXS", max_length=20
            ),
        ),
    ]
