# Generated by Django 5.2.10 on 2026-09-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sku_manager", "0002_alter_jewelrysku_name_alter_jewelrysku_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jewelrysku",
            name="is_listed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="jewelrysku",
            name="name",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="jewelrysku",
            name="number",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="jewelrysku",
            name="size",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="jewelrysku",
            name="style",
            field=models.CharField(default="", max_length=20),
        ),
    ]
