# Generated by Django 5.2.10 on 2026-09-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sku_manager", "0003_jewelrysku_is_listed_alter_jewelrysku_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jewelrysku",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
        migrations.AddField(
            model_name="jewelrysku",
            name="stock",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="jewelrysku",
            name="name",
            field=models.CharField(default="LOVE", max_length=50),
        ),
        migrations.AlterField(
            model_name="jewelrysku",
            name="number",
            field=models.CharField(default="001", max_length=10),
        ),
        migrations.AlterField(
            model_name="jewelrysku",
            name="size",
            field=models.CharField(default="2.4", max_length=20),
        ),
        migrations.AlterField(
            model_name="jewelrysku",
            name="style",
            field=models.CharField(default="ADC", max_length=20),
        ),
    ]
