# Generated by Django 5.2.10 on 2026-09-27 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sku_manager", "0005_platform_jewelrysku_purchase_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DispatchLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform_name", models.CharField(max_length=50)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "sold_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("stock_after", models.PositiveIntegerField(default=0)),
                ("dispatched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "platform",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sku_manager.platform",
                    ),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispatch_logs",
                        to="sku_manager.jewelrysku",
                    ),
                ),
            ],
            options={
                "ordering": ["-dispatched_at"],
            },
        ),
    ]
