# Generated by Django 5.2.10 on 2026-09-28 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sku_manager", "0006_dispatchlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageBox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("color_tag", models.CharField(default="amber", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="jewelrysku",
            name="section_name",
            field=models.CharField(default="Section A", max_length=30),
        ),
        migrations.AddField(
            model_name="jewelrysku",
            name="storage_box",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="skus",
                to="sku_manager.storagebox",
            ),
        ),
    ]
