# Generated by Django 5.2.10 on 2026-10-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sku_manager", "0007_storagebox_jewelrysku_section_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name", models.CharField(default="TATKAL PICK", max_length=100)),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        default="Universal Inventory & Dispatch",
                        max_length=150,
                    ),
                ),
                ("currency_symbol", models.CharField(default="₹", max_length=10)),
                ("low_stock_threshold", models.PositiveIntegerField(default=5)),
                (
                    "support_contact",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
