# Generated by Django 5.2.10 on 2026-10-01 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sku_manager", "0008_appsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="jewelrysku",
            name="batch_no",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="appsettings",
            name="tagline",
            field=models.CharField(
                blank=True, default="Universal Stock & Fast Dispatch", max_length=150
            ),
        ),
        migrations.AlterField(
            model_name="jewelrysku",
            name="category",
            field=models.CharField(
                choices=[
                    ("APP", "APP - Apparel / Clothing"),
                    ("ACC", "ACC - Accessories"),
                    ("ELC", "ELC - Electronics / Gadgets"),
                    ("FTW", "FTW - Footwear"),
                    ("HOM", "HOM - Home & Living"),
                    ("BEA", "BEA - Beauty & Care"),
                    ("NCK", "NCK - Necklace / Chain"),
                    ("BGL", "BGL - Bangles / Kada"),
                    ("GEN", "GEN - General Goods"),
                ],
                default="GEN",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="jewelrysku",
            name="color",
            field=models.CharField(
                choices=[
                    ("BLK", "BLK - Black"),
                    ("WHT", "WHT - White"),
                    ("BLU", "BLU - Blue"),
                    ("RED", "RED - Red"),
                    ("GRN", "GRN - Green"),
                    ("GLD", "GLD - Gold"),
                    ("SLV", "SLV - Silver"),
                    ("BRN", "BRN - Brown"),
                    ("MTC", "MTC - Multi-Color"),
                ],
                default="BLK",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="jewelrysku",
            name="name",
            field=models.CharField(default="ITEM", max_length=50),
        ),
        migrations.AlterField(
            model_name="jewelrysku",
            name="section_name",
            field=models.CharField(blank=True, default="Section A", max_length=50),
        ),
        migrations.AlterField(
            model_name="jewelrysku",
            name="size",
            field=models.CharField(default="FREE", max_length=20),
        ),
        migrations.AlterField(
            model_name="jewelrysku",
            name="style",
            field=models.CharField(default="STD", max_length=20),
        ),
        migrations.AlterField(
            model_name="storagebox",
            name="color_tag",
            field=models.CharField(default="#F59E0B", max_length=20),
        ),
        migrations.CreateModel(
            name="StockBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_no", models.CharField(max_length=50)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "selling_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "section_name",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="sku_manager.jewelrysku",
                    ),
                ),
                (
                    "storage_box",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sku_manager.storagebox",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
