# Generated by Django 5.2.10 on 2026-10-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sku_manager", "0009_jewelrysku_batch_no_alter_appsettings_tagline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockbatch",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("disabled", "Disabled")],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="stockbatch",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="jewelrysku",
            name="is_listed",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="jewelrysku",
            name="section_name",
            field=models.CharField(blank=True, default="Main Section", max_length=50),
        ),
    ]
