# Generated by Django 5.2.10 on 2026-10-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sku_manager", "0010_stockbatch_status_stockbatch_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jewelrysku",
            name="design_model",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="jewelrysku",
            name="category",
            field=models.CharField(default="General", max_length=50),
        ),
        migrations.AlterField(
            model_name="jewelrysku",
            name="color",
            field=models.CharField(blank=True, default="Black", max_length=30),
        ),
        migrations.AlterField(
            model_name="jewelrysku",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="jewelrysku",
            name="section_name",
            field=models.CharField(blank=True, default="Main Slot", max_length=50),
        ),
        migrations.AlterField(
            model_name="jewelrysku",
            name="size",
            field=models.CharField(blank=True, default="Free Size", max_length=30),
        ),
        migrations.AlterField(
            model_name="jewelrysku",
            name="style",
            field=models.CharField(blank=True, default="Standard", max_length=50),
        ),
    ]
