# Generated by Django 5.2.10 on 2026-10-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sku_manager",
            "0011_jewelrysku_design_model_alter_jewelrysku_category_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="stockbatch",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="appsettings",
            name="tagline",
            field=models.CharField(
                blank=True, default="Universal Inventory & Dispatch", max_length=150
            ),
        ),
        migrations.AlterField(
            model_name="stockbatch",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="stockbatch",
            name="status",
            field=models.CharField(
                choices=[("active", "Activated"), ("disabled", "Disactivated")],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="storagebox",
            name="color_tag",
            field=models.CharField(default="#3B82F6", max_length=20),
        ),
    ]
