# Generated by Django 5.2.10 on 2026-10-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sku_manager",
            "0012_stockbatch_finished_at_alter_appsettings_tagline_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="stockbatch",
            name="supplier_name",
            field=models.CharField(
                blank=True, default="Primary Supplier", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="stockbatch",
            name="section_name",
            field=models.CharField(blank=True, default="Main Section", max_length=50),
        ),
        migrations.AlterField(
            model_name="stockbatch",
            name="status",
            field=models.CharField(
                choices=[("active", "ACTIVATED"), ("disabled", "DISACTIVATED")],
                default="active",
                max_length=20,
            ),
        ),
    ]
