# Generated by Django 5.2.10 on 2026-10-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sku_manager", "0013_stockbatch_supplier_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockbatch",
            name="sales_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
