# Generated by Django 5.2.10 on 2026-10-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sku_manager", "0014_stockbatch_sales_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="appsettings",
            name="label_logo",
            field=models.ImageField(blank=True, null=True, upload_to="branding/"),
        ),
    ]
